app/controllers/cookbooks_controller.rb, app/controllers/recipes_controller.rb, app/controllers/user_queries_controller.rb, app/models/cookbook.rb, app/models/query_recipe.rb, app/models/recipe.rb, app/models/user.rb, app/models/user_query.rb, app/views/recipes/show.html.erb, app/views/user_queries/index.html.erb, app/views/user_queries/new.html.erb, app/views/user_queries/show.html.erb, config/routes.rb, db/migrate/20210301125900_create_recipes.rb, db/migrate/20210301130847_create_cookbooks.rb, db/migrate/20210301131031_create_user_queries.rb, db/migrate/20210301135335_create_query_recipes.rb, db/schema.rb, test/controllers/cookbooks_controller_test.rb, test/controllers/recipes_controller_test.rb, test/controllers/user_queries_controller_test.rb, test/models/cookbook_test.rb, test/models/query_recipe_test.rb, test/models/recipe_test.rb, test/models/user_query_test.rb
=> Routes and controller complete

app/controllers/user_queries_controller.rb, app/views/user_queries/new.html.erb
=> Seperated view page

app/assets/stylesheets/application.scss, app/controllers/user_queries_controller.rb, app/javascript/components/init_select2.js, app/javascript/packs/application.js, app/views/user_queries/new.html.erb, package.json, yarn.lock
just the tags for the ingredients input
=> Javascript for new form

app/controllers/user_queries_controller.rb
=> fixing technical problem

app/views/recipes/show.html.erb, app/views/user_queries/index.html.erb, app/views/user_queries/new.html.erb, app/views/user_queries/show.html.erb
- link to go back to all activities
- link to save to the cookbook
=> recipe show done

app/models/user_query.rb, app/views/cookbooks/index.html.erb, app/views/user_queries/new.html.erb
Using Allison method in the cookbook index
did put the a link to the card, need to create and tested
dele button path need ti be set
=> all meth done, link card ?, delete button?

app/models/party.rb, app/models/party_ingredient.rb, app/models/party_recipe.rb, app/models/recipe.rb, app/models/user.rb, app/models/user_party.rb, app/views/user_queries/show.html.erb, config/routes.rb, db/migrate/20210303134040_create_parties.rb, db/migrate/20210303134535_create_user_parties.rb, db/migrate/20210303134731_create_party_ingredients.rb, db/migrate/20210303134934_create_party_recipes.rb, db/schema.rb, db/seeds.rb, test/models/party_ingredient_test.rb, test/models/party_recipe_test.rb, test/models/party_test.rb, test/models/user_party_test.rb
=> parties done

app/controllers/cookbooks_controller.rb, app/controllers/recipes_controller.rb, app/controllers/user_queries_controller.rb, app/javascript/components/init_select2.js, app/models/recipe.rb, app/views/recipes/new.html.erb, config/routes.rb
=> adding recipe feature complete

app/controllers/application_controller.rb, app/controllers/party_recipes_controller.rb, app/views/party_recipes/create.html.erb, app/views/party_recipes/update.html.erb, config/routes.rb, db/schema.rb, db/seeds.rb, test/controllers/party_recipe_controller_test.rb
create controller party_recipe
!!!change the schema of party_recipe "choosen" to "chosen"!!!
change the route name of party >> parties
defined the method create + update
define the authorised method in application controller
=> fetching v1.0

app/controllers/application_controller.rb, app/controllers/parties_controller.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb, app/views/parties/create.html.erb, app/views/parties/destroy.html.erb, app/views/parties/index.html.erb, app/views/parties/new.html.erb, app/views/parties/show.html.erb, app/views/user_queries/new.html.erb, config/routes.rb, db/migrate/20210303155529_add_username_to_users.rb, db/schema.rb, db/seeds.rb, test/controllers/party_controller_test.rb
added index and create to parties
added username to device to create a party
=> added index and create to parties

app/controllers/cookbooks_controller.rb, app/controllers/parties_controller.rb, app/controllers/party_ingredients_controller.rb, app/models/party.rb, app/views/parties/show.html.erb, db/schema.rb
party_ingredients controller create method
parties controller
party model
parties show
=> users adding ingredients

app/views/parties/show.html.erb
just trying to make it look a little bit nicer
added some div
=> just making it look nicer

Gemfile, Gemfile.lock, app/controllers/user_parties_controller.rb, app/mailers/application_mailer.rb, app/mailers/usermailer_mailer.rb, app/models/user.rb, app/views/parties/show.html.erb, app/views/usermailer_mailer/invitation.html.erb, app/views/usermailer_mailer/invitation.text.erb, config/environments/development.rb, test/mailers/previews/usermailer_mailer_preview.rb, test/mailers/usermailer_mailer_test.rb
=> Adding mail

app/controllers/party_ingredients_controller.rb, app/views/parties/show.html.erb, db/seeds.rb
delete btn for the ingredients
=> destroy-ingredient

app/views/parties/show.html.erb
The delete button is fixed and it worked
=> fixed not like my broken heart

app/assets/stylesheets/components/_list.scss, app/assets/stylesheets/config/_colors.scss
=> Css design

app/controllers/pages_controller.rb, app/controllers/user_parties_controller.rb, app/mailers/usermailer_mailer.rb, app/views/pages/home.html.erb, config/routes.rb
=> homepage added

app/views/parties/show.html.erb
autocomplete form on the user selection for parties complete
=> autocomplete form for users

app/assets/stylesheets/pages/_party.scss, app/controllers/parties_controller.rb, app/controllers/user_parties_controller.rb, app/models/user_party.rb, app/views/parties/show.html.erb, config/routes.rb, db/migrate/20210308094124_add_status_to_user_party.rb, db/schema.rb
- a user can accept or refuse an invite
- once answer submitted the form doesn't show anymore
- creator of the party is by default attending
- if not attending, you can't add ingredients and your name won't be displayed
- status of invited friends displayed in the "party friends div"
=> invitation to the party

app/controllers/pages_controller.rb, app/mailers/application_mailer.rb, app/mailers/usermailer_mailer.rb, app/views/cookbooks/index.html.erb, app/views/pages/dashboard.html.erb
=> dashboard done

app/assets/stylesheets/components/_button_login.scss, app/assets/stylesheets/components/_button_signup.scss, app/assets/stylesheets/components/_create_button.scss, app/assets/stylesheets/components/_delete_button.scss, app/assets/stylesheets/components/_index.scss, app/views/pages/dashboard.html.erb, app/views/pages/home.html.erb, app/views/parties/show.html.erb, app/views/user_queries/new.html.erb
=> Adding buttons

app/assets/stylesheets/components/_list.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/config/_fonts.scss, app/models/recipe.rb, app/views/parties/show.html.erb, app/views/user_queries/show.html.erb
redisegned the card from recipe
=> Card almost done

Gemfile, Gemfile.lock, config/application.rb, config/environments/production.rb
=> email set up done

app/assets/stylesheets/components/_general.scss, app/assets/stylesheets/components/_index.scss, app/views/pages/dashboard.html.erb, app/views/parties/index.html.erb, public/internal_server_error.html.erb, public/not_found.html.erb
=> scss added

app/assets/stylesheets/components/_create_button.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_party.scss, app/views/parties/show.html.erb
- some css
- some rows
- some scroll
- some grid
=> party show page

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_list.scss, app/assets/stylesheets/components/_list_party.scss, app/controllers/pages_controller.rb, app/views/cookbooks/index.html.erb, app/views/pages/dashboard.html.erb, app/views/user_queries/show.html.erb
dashboard have change because the cards
cookbook also
query also
=> cards and dashboard V1

app/assets/stylesheets/pages/_party.scss, app/views/parties/show.html.erb, config/initializers/simple_form_bootstrap.rb
=> Invitation

app/assets/stylesheets/components/_list.scss, app/assets/stylesheets/pages/_party.scss, app/views/parties/show.html.erb
change css file party => partying-recipe+s
code parties show card list
=> css error 500 list party-show party css page

app/assets/stylesheets/components/_list.scss, app/assets/stylesheets/pages/_party.scss, app/views/parties/show.html.erb
fixing buttons on recipe cards
=> party-recipe-btn

app/assets/stylesheets/components/_list_party.scss, app/views/pages/dashboard.html.erb, app/views/parties/index.html.erb
Cards are now really flex in the dashboard.
Party index looks better
=> dashboard ajusted

app/assets/stylesheets/components/_list.scss, app/assets/stylesheets/components/_list_party.scss, app/views/parties/show.html.erb
I change the card design
deleted the border and make a better shadow
=> Card design

app/assets/stylesheets/components/_list.scss, app/assets/stylesheets/components/_list_party.scss, app/views/pages/dashboard.html.erb, app/views/parties/index.html.erb
took off the card border and better shadowing
fix the row class to "list-parties row" on page dahsboard and parties index
=> border shadow hover card

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
Worked on the front page for css
=> working on front page

app/assets/stylesheets/components/_list.scss, app/assets/stylesheets/components/_list_party.scss, app/assets/stylesheets/pages/_party.scss, app/views/parties/show.html.erb
- made recipe cards responsive
- improved the buttons on the recipe cards
=> made recipe cards responsive

app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_party.scss, app/assets/stylesheets/pages/_sign_in.scss, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb, app/views/pages/home.html.erb
=> sign in page

app/assets/stylesheets/components/_list.scss, app/assets/stylesheets/components/_list_party.scss, app/assets/stylesheets/pages/_cookbook.scss, app/assets/stylesheets/pages/_dashboard.scss, app/views/cookbooks/index.html.erb, app/views/pages/dashboard.html.erb, app/views/parties/index.html.erb
dashboard and cookbook responsive by changing the columns through the class
=> dashboard and cookbook responsive

app/assets/stylesheets/pages/_sign_in.scss
- opacity on div
- changed the border-radius so it's the same as for the landing page
=> sign in div modified

app/assets/stylesheets/pages/_dashboard.scss, app/views/pages/dashboard.html.erb
more space before the title on parties
better align count
=> the dashcount align

app/assets/stylesheets/components/_create_button.scss
white border removed on the btn
=> white border removed

app/assets/stylesheets/pages/_recipe.scss, app/views/recipes/show.html.erb
Changed the opacity and order of information
=> recipe page

app/assets/stylesheets/components/_create_button.scss, app/assets/stylesheets/components/_list_party.scss
=> parties card

app/assets/stylesheets/components/_get_recipes_btn.scss, app/assets/stylesheets/pages/_dashboard.scss
I modified the typo weight and color to have a easier reading.
change the opacity of the button of the query request.
=> dash count

app/assets/stylesheets/components/_create_button.scss, app/assets/stylesheets/components/_delete_button.scss
I change the buton opacity in the CSS file
=> butons opacity

app/assets/stylesheets/components/_list.scss, app/views/user_queries/show.html.erb
- text is centered
- text inside filter bar is centered
- submit button is centered and new css applied
=> user-query-filter-bar

app/assets/stylesheets/components/_list.scss, app/assets/stylesheets/pages/_party.scss, app/assets/stylesheets/pages/_recipe.scss, app/views/parties/show.html.erb
- btn fixed on the recipe cards in party page
- white background removed from guest and their ingredients
- participants status modified
- grid added to buttons in party-ingredient card so they're responsive
=> btn fixed on party page

app/assets/stylesheets/pages/_dashboard.scss, app/assets/stylesheets/pages/_recipe.scss
fixed the title and the font weight, color and underline of crearted and joined parties
=> fixed small changes on dashboard

app/assets/stylesheets/components/_button_login.scss, app/assets/stylesheets/components/_button_signup.scss, app/assets/stylesheets/components/_create_button.scss, app/assets/stylesheets/components/_get_recipes_btn.scss, app/assets/stylesheets/pages/_party.scss, app/assets/stylesheets/pages/_sign_in.scss
btn start party fixed
homogeneous opacity on green btn
=> buttons fixed

app/assets/stylesheets/pages/_party.scss, app/views/parties/show.html.erb
fixed the divs to be more responsive + changed some font details.
=> party page complete

app/assets/stylesheets/pages/_party.scss, app/views/parties/new.html.erb
to make it consistent with all the other pages
=> transparent card added

app/controllers/user_queries_controller.rb, app/javascript/components/init_select2.js, app/views/user_queries/show.html.erb
Diet filter fixed & removed filter label.
=> fixed the diet filter
